/**
 * CreateWallet screen shell — new-wallet onboarding flow.
 *
 * One prop-driven shell that renders four sequential steps via the `step`
 * prop:
 *   - "welcome"  — get-started splash; create new or import instead.
 *   - "reveal"   — show the freshly generated recovery phrase (gated behind a
 *                  blur/reveal tap) with a copy/back-up warning.
 *   - "confirm"  — re-enter selected words to prove the phrase was saved.
 *   - "password" — set + confirm the local unlock password.
 *
 * PURE PRESENTATION. The mnemonic is generated by @luxwallet/sdk and passed in
 * via `mnemonicWords`; reveal state, the confirm slots, the typed password, and
 * all validation (`error`, `canContinue`) are computed by the app and handed
 * down. This component never generates entropy, derives keys, hashes the
 * password, or persists anything — it only renders and fires callbacks.
 */
import { XStack, YStack, Text, Input } from "@hanzo/gui"
import { Card } from "../components/Card"
import { Button } from "../components/Button"
import { ScreenScaffold } from "../components/ScreenScaffold"

/** Which onboarding step to render. */
export type CreateWalletStep = "welcome" | "reveal" | "confirm" | "password"

/**
 * One word-confirmation slot on the "confirm" step. The app decides which
 * positions to quiz (`index` is the 1-based word number) and tracks the typed
 * `value`; `expected` is an optional per-slot correctness flag the app may set
 * once the value matches, used purely to tint the field.
 */
export interface ConfirmSlot {
  /** 1-based position of the word within the phrase (e.g. 3 → "word #3"). */
  index: number
  /** True when `value` matches the expected word (drives the success tint). */
  expected?: boolean
  /** Currently typed value for this slot. */
  value: string
}

export interface CreateWalletProps {
  /** Which step of the flow to show. */
  step: CreateWalletStep

  // --- welcome -------------------------------------------------------------
  /** Start creating a brand-new wallet (advance from the welcome splash). */
  onCreate?: () => void
  /** Switch to the import-existing-wallet flow instead. */
  onImportInstead?: () => void

  // --- reveal --------------------------------------------------------------
  /** The generated recovery phrase, one word per entry (from the SDK). */
  mnemonicWords?: string[]
  /** Whether the phrase is currently revealed (else it stays blurred). */
  revealed?: boolean
  /** Reveal the phrase (the app flips `revealed`). */
  onReveal?: () => void

  // --- confirm -------------------------------------------------------------
  /** Word slots to quiz the user on before continuing. */
  confirmSlots?: ConfirmSlot[]
  /** Fired as the user edits a confirm slot's value. */
  onChangeConfirmSlot?: (index: number, value: string) => void

  // --- password ------------------------------------------------------------
  password?: string
  confirmPassword?: string
  onChangePassword?: (next: string) => void
  onChangeConfirmPassword?: (next: string) => void

  // --- shared --------------------------------------------------------------
  /** Validation/error message for the current step, rendered inline. */
  error?: string
  /** Whether the primary action is enabled for the current step. */
  canContinue: boolean
  /** Advance from the current step (label adapts per step). */
  onContinue: () => void
  /** Optional back navigation (shown in the header when provided). */
  onBack?: () => void
}

/** Per-step header title + primary button label. */
const STEP_META: Record<CreateWalletStep, { title: string; cta: string }> = {
  welcome: { title: "Create a wallet", cta: "Create new wallet" },
  reveal: { title: "Your recovery phrase", cta: "I've saved it" },
  confirm: { title: "Confirm your phrase", cta: "Confirm" },
  password: { title: "Set a password", cta: "Create wallet" },
}

export function CreateWallet(props: CreateWalletProps): React.JSX.Element {
  const {
    step,
    onCreate,
    onImportInstead,
    mnemonicWords = [],
    revealed,
    onReveal,
    confirmSlots = [],
    onChangeConfirmSlot,
    password = "",
    confirmPassword = "",
    onChangePassword,
    onChangeConfirmPassword,
    error,
    canContinue,
    onContinue,
    onBack,
  } = props

  const meta = STEP_META[step]

  // The welcome step uses a bespoke footer (two stacked CTAs); every other step
  // shares the single primary-action footer gated by `canContinue`.
  const footer =
    step === "welcome" ? (
      <YStack gap="$2">
        <Button tone="primary" onPress={onCreate} testID="create-wallet-create">
          {meta.cta}
        </Button>
        {onImportInstead ? (
          <Button
            tone="secondary"
            onPress={onImportInstead}
            testID="create-wallet-import"
          >
            Import an existing wallet
          </Button>
        ) : null}
      </YStack>
    ) : (
      <Button
        tone="primary"
        disabled={!canContinue}
        onPress={onContinue}
        testID="create-wallet-continue"
      >
        {meta.cta}
      </Button>
    )

  return (
    <ScreenScaffold title={meta.title} onBack={onBack} footer={footer}>
      {step === "welcome" ? (
        <WelcomeStep />
      ) : step === "reveal" ? (
        <RevealStep words={mnemonicWords} revealed={revealed} onReveal={onReveal} />
      ) : step === "confirm" ? (
        <ConfirmStep slots={confirmSlots} onChangeSlot={onChangeConfirmSlot} />
      ) : (
        <PasswordStep
          password={password}
          confirmPassword={confirmPassword}
          onChangePassword={onChangePassword}
          onChangeConfirmPassword={onChangeConfirmPassword}
        />
      )}

      {error ? (
        <Text fontSize={13} color="$statusCritical" textAlign="center">
          {error}
        </Text>
      ) : null}
    </ScreenScaffold>
  )
}

/* --------------------------------------------------------------------------
 * Step bodies — small private components keep the switch above readable. Each
 * is pure layout over the shared primitives.
 * ------------------------------------------------------------------------ */

function WelcomeStep(): React.JSX.Element {
  return (
    <>
      <Card>
        <Text fontSize={22} fontWeight="700" color="$neutral1">
          Welcome to your wallet
        </Text>
        <Text fontSize={14} color="$neutral2">
          Create a new self-custodial wallet. You'll get a recovery phrase to back
          up, then set a password to unlock it on this device.
        </Text>
      </Card>

      <Card title="Before you start">
        <Bullet>You alone hold the keys — no one can recover them for you.</Bullet>
        <Bullet>Write your recovery phrase down and store it offline.</Bullet>
        <Bullet>Never share your phrase or password with anyone.</Bullet>
      </Card>
    </>
  )
}

function RevealStep({
  words,
  revealed,
  onReveal,
}: {
  words: string[]
  revealed?: boolean
  onReveal?: () => void
}): React.JSX.Element {
  return (
    <>
      <Card>
        <Text fontSize={13} color="$statusWarning">
          ● Anyone with this phrase can take your funds.
        </Text>
        <Text fontSize={13} color="$neutral2">
          Write these {words.length || 12} words down in order and keep them
          somewhere safe and offline.
        </Text>
      </Card>

      <Card title="Recovery phrase">
        {revealed ? (
          <XStack flexWrap="wrap" gap="$2" testID="create-wallet-phrase">
            {words.map((word, i) => (
              <XStack
                key={`${i}:${word}`}
                alignItems="center"
                gap="$2"
                paddingVertical="$2"
                paddingHorizontal="$3"
                borderRadius="$4"
                backgroundColor="$surface3"
                testID={`create-wallet-word-${i + 1}`}
              >
                <Text fontSize={12} color="$neutral2">
                  {i + 1}
                </Text>
                <Text fontSize={14} fontWeight="600" color="$neutral1">
                  {word}
                </Text>
              </XStack>
            ))}
          </XStack>
        ) : (
          <YStack
            alignItems="center"
            justifyContent="center"
            gap="$2"
            paddingVertical="$6"
            borderRadius="$4"
            backgroundColor="$surface3"
          >
            <Text fontSize={14} color="$neutral2">
              Tap to reveal your phrase
            </Text>
            <Button
              tone="secondary"
              full={false}
              size="$3"
              onPress={onReveal}
              testID="create-wallet-reveal"
            >
              Reveal phrase
            </Button>
          </YStack>
        )}
      </Card>
    </>
  )
}

function ConfirmStep({
  slots,
  onChangeSlot,
}: {
  slots: ConfirmSlot[]
  onChangeSlot?: (index: number, value: string) => void
}): React.JSX.Element {
  return (
    <Card title="Confirm your phrase">
      <Text fontSize={13} color="$neutral2">
        Type the requested words to confirm you've saved your recovery phrase.
      </Text>
      {slots.map((slot) => (
        <YStack key={slot.index} gap="$1">
          <Text fontSize={12} color="$neutral2">
            Word #{slot.index}
          </Text>
          <Input
            value={slot.value}
            onChangeText={(next: string) => onChangeSlot?.(slot.index, next)}
            placeholder={`Word #${slot.index}`}
            borderColor={slot.expected ? "$statusSuccess" : "$borderColor"}
            testID={`create-wallet-confirm-${slot.index}`}
          />
        </YStack>
      ))}
    </Card>
  )
}

function PasswordStep({
  password,
  confirmPassword,
  onChangePassword,
  onChangeConfirmPassword,
}: {
  password: string
  confirmPassword: string
  onChangePassword?: (next: string) => void
  onChangeConfirmPassword?: (next: string) => void
}): React.JSX.Element {
  return (
    <>
      <Card title="Unlock password">
        <Text fontSize={13} color="$neutral2">
          This password unlocks the wallet on this device. It can't be recovered —
          if you forget it, restore from your recovery phrase.
        </Text>
        <YStack gap="$1">
          <Text fontSize={12} color="$neutral2">
            Password
          </Text>
          <Input
            value={password}
            onChangeText={(next: string) => onChangePassword?.(next)}
            placeholder="Enter a password"
            secureTextEntry
            testID="create-wallet-password"
          />
        </YStack>
        <YStack gap="$1">
          <Text fontSize={12} color="$neutral2">
            Confirm password
          </Text>
          <Input
            value={confirmPassword}
            onChangeText={(next: string) => onChangeConfirmPassword?.(next)}
            placeholder="Re-enter your password"
            secureTextEntry
            testID="create-wallet-confirm-password"
          />
        </YStack>
      </Card>
    </>
  )
}

/** Small labeled bullet row, matching the screens' neutral copy style. */
function Bullet({ children }: { children: React.ReactNode }): React.JSX.Element {
  return (
    <XStack gap="$2" alignItems="flex-start">
      <Text fontSize={13} color="$neutral2">
        •
      </Text>
      <Text fontSize={13} color="$neutral1" flex={1}>
        {children}
      </Text>
    </XStack>
  )
}
